@host = http://localhost
@port = 3000
@url = {{host}}:{{port}}

@adminToken = {{login.response.body.token}}

### Token megszerzése 

# @name login
POST {{url}}/api/auth/login
Content-Type: application/json

{
  "email": "teszt@example.com",
  "password": "jelszo123"
}


### Összes kategória lekérése
GET {{url}}/api/categories
Content-Type: application/json

### Egy kategória részletei
GET {{url}}/api/categories/72ffae80-8e7f-4d82-9a52-4a36b763e967
Content-Type: application/json

### Új kategória létrehozása

# @name category
POST {{url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Tesz Kategória",
  "parent_id": null
}

### Al-kategória létrehozása (CRASH LEKEZELÉSE)
POST {{url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Férfi pólók",
  "parent_id": 1
}

### Kategória módosítása
PATCH {{url}}/api/categories/72ffae80-8e7f-4d82-9a52-4a36b763e967
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Férfi pólók - akció"
}