@host = http://localhost
@port = 3000
@url = {{host}}:{{port}}

@userToken = {{login.response.body.token}}

# @name login
POST {{url}}/api/auth/login
Content-Type: application/json

{
  "email": "teszt@example.com",
  "password": "jelszo123"
}

### Egy termék összes értékelése
GET {{url}}/api/reviews/product/207c07f9-8ccc-4d97-8a45-795ab2a4f3c0

### Új értékelés hozzáadása
POST {{url}}/api/reviews/product/207c07f9-8ccc-4d97-8a45-795ab2a4f3c0
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "rating": 5,
  "comment": "Nagyon tetszik, gyors szállítás!"
}

### Értékelés módosítása (saját)
PATCH {{url}}/api/reviews/0e48494c-c3dd-4c97-aba1-161f52ef3988
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "rating": 4,
  "comment": "Jó, de a méret kicsit kicsi volt"
}

### Értékelés törlése
DELETE {{url}}/api/reviews/0e48494c-c3dd-4c97-aba1-161f52ef3988
Authorization: Bearer {{userToken}}