@host = http://localhost
@port = 3000
@url = {{host}}:{{port}}


@adminToken = {{login.response.body.token}}
@userToken = {{login.response.body.token}}

# @name login
POST {{url}}/api/auth/login
Content-Type: application/json

{
  "email": "teszt@example.com",
  "password": "jelszo123"
}

### Saját profil lekérése (auth kell)
GET {{url}}/api/users/profile
Authorization: Bearer {{userToken}}

### Összes felhasználó listázása (csak admin)
GET {{url}}/api/users
Authorization: Bearer {{adminToken}}

### Egy konkrét felhasználó adatainak lekérése (admin vagy saját maga)
GET {{url}}/api/users/144c8488-9550-4873-bc0a-b30867f27ea8
Authorization: Bearer {{adminToken}}

### Saját adatok módosítása (pl. név vagy email váltás)
PATCH {{url}}/api/users/profile
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "name": "Teszt User Új Név",
  "email": "email@example.com"
}
### Felhasználó törlése (csak admin!)
DELETE {{url}}/api/users/ed10324a-91c9-4a78-97d9-d18d5f352ea2
Authorization: Bearer {{adminToken}}

### Role módosítása
PATCH {{url}}/api/users/6f4f564a-69d2-4a8f-bc0a-e8881863519b/role
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "role": "admin"
}
